ND.Web/ND.FluentTaskScheduling.Web/Controllers/TaskController.cs
using ND.FluentTaskScheduling.Model;
using ND.FluentTaskScheduling.Model.enums;
using ND.FluentTaskScheduling.Model.request;
using ND.FluentTaskScheduling.Model.response;
using ND.FluentTaskScheduling.TaskInterface;
using ND.FluentTaskScheduling.Web.App_Start;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ND.FluentTaskScheduling.Web.Controllers
{
    public class TaskController : BaseController
    {
        public TaskController()
        {
            ViewBag.NodeList = new List<NodeDetailDto>();
            ResponseBase<PageInfoResponse<List<NodeDetailDto>>> nodelist = PostToServer<PageInfoResponse<List<NodeDetailDto>>, LoadNodeListRequest>(ClientProxy.LoadNodeList_Url, new LoadNodeListRequest() { Source = Source.Web });
            if (nodelist.Status == ResponesStatus.Success)
            {
                ViewBag.NodeList = nodelist.Data.aaData;
            }
        }
        // GET: Task
        public ActionResult Index(int taskid=-1,int nodeid=-1)
        {
            ViewBag.TaskList = new List<TaskListDto>();
            ResponseBase<PageInfoResponse<List<TaskListDto>>> tasklist2 = PostToServer<PageInfoResponse<List<TaskListDto>>, LoadTaskListRequest>(ClientProxy.LoadTaskList_Url, new LoadTaskListRequest() { Source = Source.Web });
            if (tasklist2.Status == ResponesStatus.Success)
            {
                ViewBag.TaskList = tasklist2.Data.aaData;
            }
            string daterange = DateTime.Now.AddYears(-1).ToString("yyyy-MM-dd") + "/" + DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.NodeId = nodeid.ToString();
            ViewBag.TaskCreateTimeRange = daterange;
            ViewBag.TaskName = "";
            ViewBag.TaskExecuteStatus = "-1";
            ViewBag.TaskSchduleStatus = "-1";
            ViewBag.TaskId = taskid;
            ViewBag.TaskType = "-1";
            return View();
            //LoadTaskListRequest request = new LoadTaskListRequest()
            //{
            //    NodeId=int.Parse(ViewBag.NodeId),
            //    Source= Source.Web,
            //    TaskCreateTimeRange = ViewBag.TaskCreateTimeRange,
            //    TaskName=ViewBag.TaskName,
            //    TaskExecuteStatus = int.Parse(ViewBag.TaskExecuteStatus),
            //    TaskSchduleStatus = int.Parse(ViewBag.TaskSchduleStatus)
            //};
            //ResponseBase<LoadTaskListResponse> tasklist = PostToServer<LoadTaskListResponse, LoadTaskListRequest>(ClientProxy.LoadTaskList_Url, request);
            //if(tasklist.Status != ResponesStatus.Success)
            //{
            //    return View(new List<TaskListDto>());
            //}
            //return View(tasklist.Data.TaskList);
        }

        [HttpPost]
        public JsonResult Index(LoadTaskListRequest request)
        {
           
            ViewBag.NodeId = request.NodeId.ToString();
            ViewBag.TaskCreateTimeRange = request.TaskCreateTimeRange.ToString();
            ViewBag.TaskName = request.TaskName == null?"":request.TaskName.ToString();
            ViewBag.TaskExecuteStatus = request.TaskExecuteStatus.ToString();
            ViewBag.TaskSchduleStatus = request.TaskSchduleStatus.ToString();
            ViewBag.TaskId = request.TaskId.ToString();
            ViewBag.TaskType = request.TaskType.ToString();
            request.TaskCreateTimeRange = request.TaskId <= 0 ? request.TaskCreateTimeRange : "1900-01-01/2099-12-30";

            ResponseBase<PageInfoResponse<List<TaskListDto>>> tasklist = PostToServer<PageInfoResponse<List<TaskListDto>>, LoadTaskListRequest>(ClientProxy.LoadTaskList_Url, request);
            if (tasklist.Status != ResponesStatus.Success)
            {
                return Json(new
                {
                    sEcho = 0,
                    iTotalRecords = 0,
                    iTotalDisplayRecords = 0,
                    aaData = new List<string>()
                });
            }
            return Json(tasklist.Data);
        }

        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(HttpPostedFileBase TaskDllStream, AddTaskRequest model)
        {
           
            model.Source = Source.Web;
            if (TaskDllStream != null)
            {
               
                Stream dll = TaskDllStream.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                model.TaskDll = dllbyte;
            }
            model.AdminId =  UserInfo.id.ToString();
            model.AlarmUserId = Request.Form["AlarmUserId"] == null ? "" : Request.Form["AlarmUserId"].ToString();
            model.IsEnabledAlarm = Request.Form["IsEnabledAlarm"] == null ? 0 : (Request.Form["IsEnabledAlarm"].ToString().ToLower() == "on" ? 1 : 0);
            ResponseBase<AddTaskResponse> tasklist = PostToServer<AddTaskResponse, AddTaskRequest>(ClientProxy.AddTask_Url, model);
            if (tasklist.Status != ResponesStatus.Success)
            {
                return View(new List<tb_task>());
            }
            return RedirectToAction("index");
        }

        public ActionResult Edit(int taskid=0,int taskversionid=0)
        {
            ViewBag.taskid = taskid;
            ViewBag.taskversionid = taskversionid;
            var taskversionreq = new LoadTaskVersionRequest() { TaskId = taskid, TaskVersionId = taskversionid, Source = Source.Web };
            var r = PostToServer<LoadTaskVersionResponse, LoadTaskVersionRequest>(ClientProxy.TaskVersionDetail_Url, taskversionreq);
                if (r.Status != ResponesStatus.Success)
                {
                    return View(new LoadTaskVersionResponse());
                }
            return View(r.Data);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase TaskDllStream, UpdateTaskInfoRequest model)
        {
            model.Source = Source.Web;
            model.AlarmUserId = Request.Form["AlarmUserId"]==null?"":Request.Form["AlarmUserId"].ToString();
            model.IsEnabledAlarm = Request.Form["IsEnabledAlarm"] == null ? 0 : (Request.Form["IsEnabledAlarm"].ToString().ToLower() == "on" ? 1 : 0);
           
            if (TaskDllStream != null)
            {
                string filename = TaskDllStream.FileName;
                Stream dll = TaskDllStream.InputStream;
                byte[] dllbyte = new byte[dll.Length];
                dll.Read(dllbyte, 0, Convert.ToInt32(dll.Length));
                model.TaskDll = dllbyte;
                
            }
           // model.TaskId =int.Parse(ViewBag.taskid);
           // model.TaskVersionId = int.Parse(ViewBag.taskversionid);
            ResponseBase<UpdateTaskInfoResponse> tasklist = PostToServer<UpdateTaskInfoResponse, UpdateTaskInfoRequest>(ClientProxy.UpdateTask_Url, model);
            if (tasklist.Status != ResponesStatus.Success)
            {
                //ModelState.AddModelError("AddTaskFailed", tasklist.Msg);
                return View(new List<tb_task>());
              
            }
            return RedirectToAction("/index");
        }

        #region 更新任务状态
        [HttpPost]
        public JsonResult ChangeTaskStatus(string nodeid, string taskid, string taskversionid, string commandname)
        {
           
            try
            {
                //添加启动命令 
                AddCommandQueueItemRequest model = new AddCommandQueueItemRequest()
                {
                    AdminId = "0",
                    CommandName = (CommandName)(int.Parse(commandname)),
                    CommandParam = "",
                    NodeId = nodeid,
                    TaskId = taskid,
                    TaskVersionId = taskversionid,
                };
                ResponseBase<AddCommandQueueItemResponse> rep = PostToServer<AddCommandQueueItemResponse, AddCommandQueueItemRequest>(ClientProxy.AddCommandQueue_Url, model);

                
               // var ret = JsonConvert.SerializeObject(rep, setting);
               // Response.Write(ret);
              //  return Json(rep, JsonRequestBehavior.AllowGet);
               // return Json(rep);
                return Json(rep);
            }
            catch(Exception ex)
            {
                var rep2=new ResponseBase<AddCommandQueueItemResponse>() { Status = ResponesStatus.Exception, Msg = ex.Message };
                return Json(rep2);
               // var ret2 = JsonConvert.SerializeObject(rep2, setting);
               // var ret2 = JsonConvert.SerializeObject(rep2, setting);
               // return Json(rep2,JsonRequestBehavior.AllowGet);
                //Response.Write(ret2);
                //return Json(rep2, JsonRequestBehavior.AllowGet);
            }
        } 
        #endregion
    }
}

ND.Web/ND.FluentTaskScheduling.Web/Views/Task/Add.cshtml
@model ND.FluentTaskScheduling.Model.request.AddTaskRequest
@using ND.FluentTaskScheduling.Model.response
@using ND.FluentTaskScheduling.Model;
@using ND.FluentTaskScheduling.Model.enums
@{
    ViewBag.Title = "添加任务";
    List<NodeDetailDto> nodelist = ViewBag.NodeList as List<NodeDetailDto>;
    List<tb_user> userlist = ViewBag.UserList as List<tb_user>;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1>
       添加任务
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 任务管理</a></li>
        <li><a href="#">添加任务</a></li>
    </ol>
</section>

@using (Html.BeginForm("Add", "Task", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row">


        <div class="box box-primary col-md-6 pull-right">
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>任务名称:</label>
                        <input type="text"  name="TaskName" class="form-control" placeholder="任务名称:测试任务">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务命名空间:</label>
                        <input type="text" class="form-control" name="TaskNameSpace" placeholder="任务命名空间:ND.FluentTaskScheduling.TaskDemo">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务类名:</label>
                        <input type="text" class="form-control" name="TaskMainClassName" placeholder="任务类名:ND.FluentTaskScheduling.TaskDemo.DemoTask">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务节点</label>
                        <select class="form-control select2" name="NodeId" data-placeholder="任务节点">
                            @for (int i = 0; i < nodelist.Count; i++)
                            {
                                <option value="@nodelist[i].NodeDetail.id">@nodelist[i].NodeDetail.nodename</option>
                            }
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label>任务描述:</label>
                        <textarea class="form-control" name="TaskDescription" rows="3" placeholder="任务描述"></textarea>
                    </div>

                    <div class="form-group col-md-6">
                        <label>任务参数:</label>
                        <textarea class="form-control" name="TaskParams" rows="3" placeholder="任务参数：{aa:123}"></textarea>
                    </div>
                </div>

                

                <div class="row">
                    <div class="form-group col-md-6">
                        <label>任务dll压缩包名称:</label>
                        <input type="text" class="form-control" name="TaskDllFileName" placeholder="任务dll压缩包名称：ND.FluentTaskScheduling.TaskDemo.rar">
                    </div>

                    <div class="form-group col-md-6">
                        <label>上传任务压缩包:</label>
                        <input type="file" class="form-control" name="TaskDllStream" placeholder="任务dll压缩包名称">
                    </div>
                </div>

               

              

                <div class="row">

                    <div class="form-group col-md-6">
                        <label>任务备注:</label>
                        <textarea class="form-control" name="TaskRemark" rows="3" placeholder="任务备注"></textarea>
                    </div>

                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label>任务类型:</label><br/>
                            @foreach (var o in (ND.FluentTaskScheduling.Helper.EnumHelper<ND.FluentTaskScheduling.Model.enums.TaskType>.GetAllEnumsOfList2()))
                            {
                                <label class="margin-r-5">
                                    <input type="radio" name="TaskType"  @(((int)TaskType.SchedulingTask).ToString() == o.Value ? "checked=''checked" : "") value="@o.Value" class="flat-red">&nbsp&nbsp<span>@o.Text</span>
                                </label>
                            }
                        </div>

                        <div class="tasktypebox">
                            <div class="form-group">
                                @*<label>任务Corn表达式:</label>*@
                                <input type="text" class="form-control" name="TaskCorn" placeholder="任务Corn表达式(每5秒执行一次):0/5 * * * * ?">
                            </div>
                        </div>
                    </div>

                   
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label>
                                <input type="checkbox" id="isenabledAlarm" name="IsEnabledAlarm" checked="checked" class="flat-red">&nbsp&nbsp是否启用报警<br />
                            </label>
                        </div>
                        <div class="alarmbox">
                            <div class="form-group">
                                @foreach (var o in (ND.FluentTaskScheduling.Helper.EnumHelper<ND.FluentTaskScheduling.Helper.AlarmType>.GetAllEnumsOfList2()))
                                {
                                    <label class="margin-r-5">
                                        <input type="radio" name="AlarmType" @("0" == o.Value ? "checked=''checked" : "") value="@o.Value" class="flat-red">&nbsp&nbsp<span>@o.Text</span>
                                    </label>
                                }
                            </div>
                            <div class="form-group">
                                <label>
                                    报警人
                                    <select id="selalarmlist" class="form-control select2" name="AlarmUserId" multiple="multiple" data-placeholder="选择报警人" style="width: 100%;">
                                        @for (int i = 0; i < userlist.Count; i++)
                                        {
                                            <option value="@userlist[i].id">@userlist[i].realname.ToString()</option>
                                        }
                                    </select>
                                </label>
                            </div>
                        </div>

                    </div>


                </div>
               

                <div class="row">
                    <div class="form-group col-md-3">
                        
                        <a href="../Task/Index" class="btn pull-right">返回列表</a>
                        <button type="submit" class="btn margin-r-5 btn-primary pull-right">保存</button>
                    </div>
                </div>

            </div>

        </div>
    </div>

}


<script>

    $(function () {
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });


        $('#isenabledAlarm').on('ifChecked', function (event) {
            $(".alarmbox").show();
        });
        $('#isenabledAlarm').on('ifUnchecked', function (event) {
            $(".alarmbox").hide();
        });
        $('input[name=TaskType]').on('ifChecked', function (event) {
            if ($(this).val() == '@((int)TaskType.SchedulingTask)')
            {
                $(".tasktypebox").show();
            }
            else
            {
                $(".tasktypebox").hide();
            }
           
        });
       




    })
</script>

ND.Web/ND.FluentTaskScheduling.Web/Views/Task/Edit.cshtml
@model ND.FluentTaskScheduling.Model.response.LoadTaskVersionResponse
@using ND.FluentTaskScheduling.Model.response
@using ND.FluentTaskScheduling.Model;
@using ND.FluentTaskScheduling.Model.enums
@{
    ViewBag.Title = "编辑任务";
    List<NodeDetailDto> nodelist = ViewBag.NodeList as List<NodeDetailDto>;
    List<tb_user> userlist = ViewBag.UserList as List<tb_user>;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Task", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" value="@Model.TaskDetail.id" name="TaskId" />
    <input type="hidden" value="@Model.TaskVersionDetail.id" name="TaskVersionId" />
    <div class="row">


        <div class="box box-primary col-md-6 pull-right">
            <div class="box-body">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label>任务名称:</label>
                        <input type="text" name="TaskName" class="form-control" value="@Model.TaskDetail.taskname" placeholder="任务名称">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务命名空间:</label>
                        <input type="text" class="form-control" name="TaskNameSpace" value="@Model.TaskDetail.tasknamespace" placeholder="任务命名空间">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务类名:</label>
                        <input type="text" class="form-control" name="TaskMainClassName" value="@Model.TaskDetail.taskclassname" placeholder="任务类名">
                    </div>

                    <div class="form-group col-md-3">
                        <label>任务节点</label>
                        <select class="form-control select2" name="NodeId" data-placeholder="任务节点">
                            @for (int i = 0; i < nodelist.Count; i++)
                            {
                                <option value="@nodelist[i].NodeDetail.id" @((Model.TaskVersionDetail.nodeid + "") == nodelist[i].NodeDetail.id.ToString() ? "selected='selected'" : "")>@nodelist[i].NodeDetail.nodename</option>
                            }
                        </select>
                    </div>

                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label>任务描述:</label>
                        <textarea class="form-control" name="TaskDescription" rows="3"  placeholder="任务描述">@Model.TaskDetail.taskdescription</textarea>
                    </div>
                    <div class="form-group col-md-6">
                        <label>任务参数:</label>
                        <textarea class="form-control" name="TaskParams" rows="3" placeholder="任务参数">@Model.TaskVersionDetail.taskparams</textarea>
                    </div>
                </div>

              

                <div class="row">
                    <div class="form-group col-md-6">
                        <label>任务dll压缩包名称:</label>
                        <input type="text" class="form-control" name="TaskDllFileName" value="@Model.TaskVersionDetail.zipfilename" placeholder="任务dll压缩包名称">
                    </div>
                    <div class="form-group col-md-6">
                        <label>上传任务压缩包:</label>
                        <input type="file" class="form-control" name="TaskDllStream" placeholder="任务dll压缩包名称">
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label>任务备注:</label>
                        <textarea class="form-control" name="TaskRemark" rows="3" placeholder="任务备注">"@Model.TaskDetail.taskremark"</textarea>
                    </div>

                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label>任务类型:</label><br />
                            @foreach (var o in (ND.FluentTaskScheduling.Helper.EnumHelper<TaskType>.GetAllEnumsOfList2()))
                            {
                                <label class="margin-r-5">
                                    <input type="radio" name="TaskType" @(Model.TaskDetail.tasktype.ToString() == o.Value ? "checked=''checked" : "") value="@o.Value" class="flat-red">&nbsp&nbsp<span>@o.Text</span>
                                </label>
                            }
                        </div>

                        <div class="tasktypebox">
                            <div class="form-group">
                                @*<label>任务Corn表达式:</label>*@
                                <input type="text" class="form-control" name="TaskCorn" value="@Model.TaskVersionDetail.taskcron" placeholder="任务Corn表达式">
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <div class="form-group">
                            <label>
                                <input type="checkbox"  name="IsEnabledAlarm" class="flat-red"/>&nbsp&nbsp是否启用报警<br />
                            </label>
                        </div>
                        <div  class="alarmbox">
                            <div class="form-group">
                                @foreach (var o in (ND.FluentTaskScheduling.Helper.EnumHelper<ND.FluentTaskScheduling.Helper.AlarmType>.GetAllEnumsOfList2()))
                                {
                                    <label class="margin-r-5">
                                        <input type="radio" name="AlarmType" @(Model.TaskDetail.alarmtype.ToString() == o.Value ? "checked=''checked" : "") value="@o.Value" class="flat-red">&nbsp&nbsp<span>@o.Text</span>
                                    </label>
                                }
                            </div>
                            <div class="form-group">
                                <label>
                                    报警人
                                    <select id="selalarmlist" class="form-control select2" name="AlarmUserId" multiple="multiple" data-placeholder="选择报警人" style="width: 100%;">
                                        @for (int i = 0; i < userlist.Count; i++)
                                        {
                                            <option value="@userlist[i].id" @(Model.TaskDetail.alarmuserid.Split(',').Contains(userlist[i].id.ToString()) ? "selected='selected'" : "")>@userlist[i].realname.ToString()</option>
                                        }
                                    </select>
                                </label>
                            </div>
                        </div>

                    </div>
                </div>

               
              
                <div class="row">
                    <div class="form-group col-md-3">

                        <a href="../Task/index" class="btn pull-right">返回列表</a>
                        <button type="submit" class="btn margin-r-5 btn-primary pull-right">修改</button>
                    </div>
                </div>

            </div>

        </div>
    </div>

}

<script>

    $(function () {
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });


        $('input[name=IsEnabledAlarm]').on('ifChecked', function (event) {
            $(".alarmbox").show();


        });
        $('input[name=IsEnabledAlarm]').on('ifUnchecked', function (event) {
            $(".alarmbox").hide();
        });
       
        $('input[name=TaskType]').on('ifChecked', function (event) {
            if ($(this).val() == '@((int)TaskType.SchedulingTask)') {
                $(".tasktypebox").show();
            }
            else {
                $(".tasktypebox").hide();
            }

        });
        Init();


    })
    function Init()
    {
        if ('@Model.TaskDetail.isenablealarm' == "1") {
            $('input[name=IsEnabledAlarm]').iCheck('check');
            $(".alarmbox").show();
           
        }
        else {
            $('input[name=IsEnabledAlarm]').iCheck('uncheck');
            $(".alarmbox").hide();
        }

        if('@Model.TaskDetail.tasktype' =='@((int)TaskType.SchedulingTask)')
        {
            $(".tasktypebox").show();
        }
        else
        {
            $(".tasktypebox").hide();
        }
    }
   
</script>